name = "RPG Modpack"
author = "TheBroccoliBob & ThePotatoArchivist"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1cf98d1014c8f419cccf2a7030f5ff8bae4e387c1757978f72a55f3955bd3a1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"

[options]
acceptable-game-versions = []
