name = "RPG Modpack"
author = "TheBroccoliBob & ThePotatoArchivist"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1abf35e8146f673be57fedf66c745f9b6fed2f59bc66993363cc721c24827418"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"

[options]
acceptable-game-versions = []
